module.exports = {
  content: [
    './app/views/**/*.{erb,html}',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js'
  ],
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        righteousfellowship: {
          "primary": "#3b82f6",
          "primary-content": "#ffffff",
          "secondary": "#8b5cf6",
          "secondary-content": "#ffffff",
          "accent": "#10b981",
          "accent-content": "#ffffff",
          "neutral": "#1f2937",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f3f4f6",
          "base-300": "#e5e7eb",
          "base-content": "#1f2937",
          "info": "#3abff8",
          "info-content": "#ffffff",
          "success": "#10b981",
          "success-content": "#ffffff",
          "warning": "#fbbd23",
          "warning-content": "#1f2937",
          "error": "#ef4444",
          "error-content": "#ffffff",
        },
        "righteousfellowship-dark": {
          "primary": "#60a5fa",
          "primary-content": "#ffffff",
          "secondary": "#a78bfa",
          "secondary-content": "#ffffff",
          "accent": "#34d399",
          "accent-content": "#ffffff",
          "neutral": "#e2e8f0",
          "neutral-content": "#0f172a",
          "base-100": "#0f172a",
          "base-200": "#1e293b",
          "base-300": "#334155",
          "base-content": "#e2e8f0",
          "info": "#3abff8",
          "info-content": "#0f172a",
          "success": "#34d399",
          "success-content": "#0f172a",
          "warning": "#fbbf24",
          "warning-content": "#0f172a",
          "error": "#f87171",
          "error-content": "#0f172a",
        },
      },
    ],
    defaultTheme: "righteousfellowship",
  },
}
